### ISSUE TITLE
ValueError on C-style for loop

### ISSUE THREAD

**Issue by livibetter** [rbrich/bashtrace#1]
The following script:

``` bash
for ((i=0; i<10; i++)); do
  echo $i
done
```

caused:

``` python
% ./bashtrace.py -b : test.sh
Traceback (most recent call last):
  File "./bashtrace.py", line 54, in <module>
    main()
  File "./bashtrace.py", line 50, in main
    curses.wrapper(curses_main, bash_trace, args)
  File "/usr/lib64/python3.4/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "./bashtrace.py", line 14, in curses_main
    bash_trace.run_script(args.script, args.args, args.wrapper)
  File "/tmp/bashtrace/bashtrace/program.py", line 282, in run_script
    self.update_screen()
  File "/tmp/bashtrace/bashtrace/program.py", line 156, in update_screen
    self.refresh_sources()
  File "/tmp/bashtrace/bashtrace/program.py", line 189, in refresh_sources
    actual_height = script.draw(win, y, win_h - y, win_w)
  File "/tmp/bashtrace/bashtrace/scriptsource.py", line 167, in draw
    self.update_command_span()
  File "/tmp/bashtrace/bashtrace/scriptsource.py", line 102, in update_command_span
    col = merged_highlighted_lines.index(self.command, self._cmd_col)
ValueError: substring not found
```

**Comment by rbrich** [comment]
Reopening - even though the fix works for the one case reported, it does not work for C-style for-loops in general. Another example:

``` bash
TEXT="Hello world!"
for (( N=0 ; N < ${#TEXT} ; N++ )); do
    echo "${TEXT:N:1}"
done
```

`BASH_COMMAND` value goes through `((N=0 ))` and `((N < 12 ))`, where the exception occurs again. This means that Bash first expands the variable, then gives expanded result (unlike in most other statements where expansion happens after).

My new solution will be to not try coloring part of command, but rather mark whole line and display the command as reported by Bash in other place (for example in new status line above key hints). This solution should be simpler and more robust.
